services:
  backend:
    container_name: jazz-chat
    hostname: backend
    image: jazz-chat:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    ports:
      - ${CONTAINER_PORT}:${PORT}
    env_file:
      - .env.development
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      # wait for mongodb service ready
      # https://github.com/ufoscout/docker-compose-wait
      WAIT_HOSTS: mongodb:${DATABASE_PORT}
      WAIT_LOGGER_LEVEL: info

  mongodb:
    container_name: jazz-chat-db-dev
    hostname: mongodb
    image: mongo:7.0.5
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - chatdata:/data/db

volumes:
  chatdata:
